docon/models.py
from flask.ext.mongoengine import MongoEngine
from mongoengine.queryset import DoesNotExist
import datetime

from languages import LANGUAGES

db = MongoEngine()

OUTFORMATS = (
    ('json-ld', 'JSON-LD'),
    ('rdf', 'RDF+XML'),
    ('nt', 'N-Triples'),
    ('trix', 'TRIX'),
)

MIMES = {
    "json-ld": "application/json",
    "rdf": "application/rdf+xml",
    "default": "text/plain"
}

class EuFormat(db.Document):
    TXT = 'txt'
    CSV = 'csv'
    TSV = 'tsv'
    ODS = 'ods'
    XLS = 'xls'
    JSONLD = 'jsonld'
    XML = 'xml'
    fileformats = ((TXT, 'txt - Plain text'),
                   (CSV, 'csv - Comma Separated Values'),
                   (TSV, 'tsv - Tab Separated Values'),
                   (ODS, 'ods - Open Document Spreadsheet'),
                   (XLS, 'xls - Microsoft Excel Spreadsheet'),
                   (JSONLD, 'json-ld - JSON for Linked Data'),
                   (XML, 'XML - XML format'))

    name = db.StringField(verbose_name='Format name',
                          max_length=200,
                          unique=True)
    extension = db.StringField(verbose_name='File extension',
                               max_length=10,
                               choices=fileformats,
                               default=CSV)
    description = db.StringField(verbose_name='Description of the format',
                                 max_length=1500)
    example = db.FileField(verbose_name='Example of the format',
                           collection_name='example')

    def __unicode__(self):
        return self.name

    meta = {
        'allow_inheritance': True,
        'indexes': ['name'],
        'ordering': ['-name']
    }

class EuTemplate(db.Document):
    name = db.StringField(verbose_name='Template name',
                          max_length=200,
                          unique=True)
    text = db.StringField(verbose_name='Template')
    informat = db.ReferenceField(EuFormat,
                                 dbref=False,
                                 verbose_name='Input format')
    outformat = db.StringField(max_length=10, choices=OUTFORMATS,
                             verbose_name='Output format')
    usedTimes = db.IntField(verbose_name='Times it has been used',
                            default=0)

    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = "Conversion Template"


class TranslationRequest(db.Document):
    ERROR = "error"
    PENDING = "pending"
    SUCCESS = "success"
    INTYPES = (
        ('file', 'File'),
        ('url', 'Specify the file URL'),
        ('direct', 'Direct'),
    )

    template = db.ReferenceField(EuTemplate,
                                 verbose_name='Template used')
    input = db.StringField(verbose_name='Input')
    task_id = db.StringField(verbose_name='Task ID in Celery')
    intype = db.StringField(verbose_name='Input Type',
                            max_length=10,
                            choices=INTYPES, default='file')
    infile = db.FileField(verbose_name='Uploaded file for translation',
                          collection_name='uploads')
    outfile = db.FileField(verbose_name='Result of translation',
                           collection_name='results')
    informat = db.ReferenceField(EuFormat,
                                 verbose_name='Input format',
                                 required=False)
    outformat = db.StringField(max_length=10, choices=OUTFORMATS,
                               verbose_name='output format',
                               default='jsonld',
                               required=False)
    baseuri = db.StringField(verbose_name='Base URI',
                             max_length=200,
                             required=False)
    prefix = db.StringField(verbose_name='Prefix', max_length=20)
    language = db.StringField(verbose_name='Language of the corpus',
                              choices=LANGUAGES,
                              required=False)
    ip = db.StringField(verbose_name='Request IP')
    status = db.StringField(verbose_name='Status of the request')
    message = db.StringField(verbose_name='Return message')
    requested = db.DateTimeField(default=datetime.datetime.now)
    started = db.DateTimeField()
    finished = db.DateTimeField()


    def delete(self, *args, **kwargs):
        self.clean_files()
        super(TranslationRequest, self).delete(*args, **kwargs)

    def clean_files(self):
        self.infile.delete()
        self.outfile.delete()
        self.infile = self.outfile = None
        self.save()

    def delete(self, *args, **kwargs):
        self.clean_files()
        super(TranslationRequest, self).delete(*args, **kwargs)

    def start(self):
        self.started = datetime.datetime.now()
        self.status = self.PENDING
        self.save()

    def finish(self):
        self.finished = datetime.datetime.now()
        self.save()

    @staticmethod
    def from_params(params):
        fixed = params.copy()
        if "template" in fixed and not isinstance(fixed["template"],
                                                  db.ReferenceField):
            fixed["template"] = EuTemplate.objects.get(name=fixed["template"])
        if "informat" in fixed and not isinstance(fixed["informat"],
                                                   db.ReferenceField):
            fixed["informat"] = EuFormat.objects.get(name=fixed["informat"])
        if "input" in fixed and not isinstance(fixed["input"], basestring):
            fixed["infile"] = fixed["input"]
            del fixed["input"]
        return TranslationRequest(**fixed)

    def as_dict(self):
        return {"id": str(self.id),
                "started": self.started,
                "requested": self.requested,
                "finished": self.finished,
                "informat": self.informat.name,
                #"infile": self.infile,
                "outformat": self.outformat,
                "template": self.template.name,
                "status": self.status,
                "message": self.message}


class User(db.Document):
    login = db.StringField(unique=True)
    email = db.StringField()
    admin = db.BooleanField(default=False)
    password = db.StringField(min_length=3)

    # Flask-Login integration
    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id)

    # Required for administrative interface
    def __unicode__(self):
        return self.login

docon/forms.py
from wtforms import form, fields, validators
from flask.ext.mongoengine.wtf import model_form
from .models import User, TranslationRequest
from .models import TranslationRequest
import wtforms.fields


class LoginForm(form.Form):
    login = fields.TextField(validators=[validators.required()])
    password = fields.PasswordField(validators=[validators.required()])

    def validate_login(self, field):
        user = self.get_user()

        if user is None:
            raise validators.ValidationError('Invalid user')

        if user.password != self.password.data:
            raise validators.ValidationError('Invalid password')

    def get_user(self):
        return User.objects(login=self.login.data).first()


class RegistrationForm(form.Form):
    login = fields.TextField(validators=[validators.required()])
    email = fields.TextField()
    password = fields.PasswordField(validators=[validators.required()])

    def validate_login(self, field):
        if User.objects(login=self.login.data).count() > 0:
            raise validators.ValidationError('Duplicate username')

docon/templates/forms.py
from .models import TranslationRequest
from flask.ext.mongoengine.wtf import model_form

TRForm = model_form(TranslationRequest)

docon/__init__.py
# -*- coding: utf-8 -*-
if __name__ == '__main__':
    app = create_app()
    app.run()

docon/auth.py
import os
from flask.ext import login
from .models import User

# Initialize flask-login
def init_login(app):
    login_manager = login.LoginManager()
    login_manager.init_app(app)

    # Create user loader function
    @login_manager.user_loader
    def load_user(user_id):
        return User.objects.get(pk=user_id)

docon/views.py
# -*- coding: utf-8 -*-
from flask import (abort, Blueprint, Flask, jsonify,
                   make_response, redirect, render_template,
                   request, Response, url_for)
from utils import *
from .models import TranslationRequest, EuTemplate, EuFormat, OUTFORMATS, db
from celery.exceptions import TimeoutError
from bson.json_util import dumps
from languages import LANGUAGES
from bson import json_util
from bson import ObjectId
from gridfs import GridFS
from gridfs.errors import NoFile

import logging
logger = logging.getLogger(__name__)

frontend = Blueprint('frontend', __name__, url_prefix='')
import tasks
import models

@frontend.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # login and validate the user...
        login_user(user)
        flash("Logged in successfully.")
        return redirect(request.args.get("next") or url_for("frontend.index"))
    return render_template("login.html", form=form)

@frontend.route('/')
def home():
    return render_template('home.html')

@frontend.route('/examples/<fmt>')
def serve_example(fmt):
    try:
        example = EuFormat.objects.get(name=fmt).example.get()
        response = make_response(example.read())
        response.mimetype = example.content_type
        return response
    except (EuFormat.DoesNotExist, NoFile):
        return "No file for {}".format(fmt)
        #abort(404)

@frontend.route('/upload')
def upload():
    return render_template('upload.html',
                           languages=LANGUAGES,
                           templates=EuTemplate.objects(),
                           informats=EuFormat.objects(),
                           outformats=OUTFORMATS)

@frontend.route('/formats')
def formats():
    formats = EuFormat.objects.all()
    return render_template('formats.html', formats=formats)

@frontend.route('/api')
def api():
    return render_template('api.html')

@frontend.route('/process', methods=['POST', 'GET'])
def process():
    PARAMS = {"input": {"aliases": ("i", "input"),
                        "required": True,
                        "help": "Input text"
                        },
              "informat": {"aliases": ("f", "informat"),
                           "required": False, },
              "intype": {"aliases": ("intype", "t"),
                         "required": False,
                         "default": "direct",
                         "options": ("direct", "url", "file"),
                         },
              "outformat": {"aliases": ("outformat", "o"),
                            "default": "json-ld",
                            "required": False,
                            },
              "template": {"aliases": ("template", ),
                           "required": False
                            },
              "language": {"aliases": ("language", "l"),
                           "required": False,
                           },
              "baseuri": {"aliases": ("base", "b", "baseuri"),
                           "required": False,
                           "default": "http://demos.gsi.dit.upm.es/eurosentiment/generator/process/default#",
                            },
              "urischeme": {"aliases": ("urischeme", "u"),
                            "required": False,
                            "default": "RFC5147String",
                            "options": ("RFC5147String",)
                            },
              "timeout": {"aliases": ("timeout", ),
                          "required": False,
                          "default": "0"
                          },
              }
    try:
        params = get_params(request, PARAMS)
        if "language" in params and params["language"] == "":
            del params["language"]
        if "template" not in params:
            informat = EuFormat.objects.get(name=params["informat"])
            params["template"] = EuTemplate.objects.get(informat=informat,
                                                        outformat=params["outformat"]).name
    except ValueError as ex:
        return ex.message
    logger.info("Processing: {}".format(params))
    try:
        tr = TranslationRequest.from_params(params)
    except EuTemplate.DoesNotExist as ex:
        return ex.message, 404
    tr.ip = get_client_ip(request)
    tr.save()
    trid = tr.id
    try:
        timeout = float(params["timeout"])
        logger.info("Async")
        res = tasks.process_request.delay(trid)
        tr.task_id = res.task_id
        tr.save()
        try:
            res.get(timeout=timeout, propagate=False)
        except TimeoutError:
            pass
    except ValueError:
        tr = tasks.process_request(trid)
    return get_result(trid)

@frontend.route('/get/<translation_id>')
def get_result(translation_id):
    logger.info("Getting result for {}".format(translation_id))
    headers = {}
    mimetype = "text/html"
    try:
        tr = TranslationRequest.objects.get(id=translation_id)
        headers["Location"] = url_for("frontend.get_result",
                                    translation_id=translation_id)
        result = json.dumps(tr.as_dict(), default=json_util.default)
        status = tr.status
        if status == tr.SUCCESS:
            outfile = tr.outfile
            mimetype = models.MIMES.get(tr.outformat, models.MIMES["default"])
            status = 200
            result = outfile.get()
            logger.debug("Got response")
        elif status == tr.PENDING:
            status = 202
            logger.debug("Come back later")
        else:
            status = 500
            logger.debug("There was an error processing the request.")

    except Exception as ex:
        status = 404
        result = "Translation ID not found: {}".format(ex)
    return Response(result, status=status, headers=headers, mimetype=mimetype)

@frontend.route('/my_requests')
def my_requests():
    ip = get_client_ip(request)
    reqs = TranslationRequest.objects(ip=ip).order_by("-started")
    return jsonify(ip=ip, requests=list(req.as_dict() for req in reqs))

docon/templates/api.html
{% extends 'base.html' %}

{% block main %}
<h1>How to use the Docon's API</h1>
<p>To access the API just send a POST request to <a
    href="http://demos.gsi.dit.upm.es">http://demos.gsi.dit.upm.es</a> with
these parameters:
<dl>
    <dt>input (i):</dt>
        <dd>The original file to be translated</dd>
    <dt>informat (f):</dt>
        <dd>The format of the original file</dd>
    <dt>intype (t) [Optional]:</dt>
        <dd>
        <ul>
            <li>direct (default)</li>
            <li>url</li>
            <li>file</li>
        </ul></dd>
    <dt>outformat (o):</dt>
    <dd>
    <ul>
        <li>json-ld (default)</li>
        <li>rdfxml</li>
        <li>turtle</li>
        <li>ntriples</li>
        <li>trix</li>
    </ul></dd>
    <dt>base URI (u) [Optional]:</dt>
        <dd>base URI to use for the corpus</dd>
    <dt>prefix (p) [Optional]:</dt>
        <dd>prefix to replace the base URI</dd>
    <dt>template (t) [Optional]:<dt>
        <dd>ID of the template to use. If it is omitted, a template to convert from informat to outformat will be used, or a template from informat to another format (e.g. jsonld), with automatic conversion.
    <dt>toFile [Optional]:</dt>
        <dd>Whether the result should be sent in the response (default) or written to a file. For convenience, this value defaults to False when using the Web Form.</dd>  
</dl>
</p>
<p>On GNU/Linux, you can test the the API using <a href="http://curl.haxx.se/">curl</a>. A request would look like this:  
</p>
<pre>
<code>
curl http://demos.gsi.dit.upm.es/docon/process \
-F"intype=file" -F"informat=Example" -F"outformat=jsonld" -F"input=@input-file.csv" \
> result.jsonld
</code>
</pre>

{% endblock %}

docon/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    </head>
    <body>
    </body>
</html>


<!DOCTYPE HTML>
<html>

<head>
  <title>{% block title %}Docon{% endblock %}</title>
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href={{ url_for("static", filename="css/style.css") }} title="style" />
        {% block extra_js %}
        {% endblock %}
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <a href="http://eurosentiment.eu"><img class="eulogo" src={{ url_for("static", filename="img/logo.png") }}/></a>
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><a href="{{ url_for("frontend.home") }}">Euro<span class="logo_colour">Sentiment</span></a></h1>
          <a href="http://gsi.dit.upm.es/ontologies/marl"><img src={{ url_for("static", filename="img/marl_logo.png") }}/><h2> Generator</h2></a>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li><a href="{{ url_for("frontend.home") }}">About</a></li>
          <li><a href="{{ url_for("frontend.upload") }}">Translate</a></li>
          <li><a href="{{ url_for("frontend.formats") }}">Formats</a></li>
          <li><a href="{{ url_for("frontend.api") }}">API</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <!--<div class="sidebar">-->
        <!--[> insert your sidebar items here <]-->
        <!--<h3>Latest News</h3>-->
        <!--<h4>New Website Launched</h4>-->
        <!--<h5>August 1st, 2013</h5>-->
        <!--<p>2013 sees the redesign of our website. Take a look around and let us know what you think.<br /><a href="#">Read more</a></p>-->
        <!--<p></p>-->
        <!--<h4>New Website Launched</h4>-->
        <!--<h5>August 1st, 2013</h5>-->
        <!--<p>2013 sees the redesign of our website. Take a look around and let us know what you think.<br /><a href="#">Read more</a></p>-->
        <!--<h3>Useful Links</h3>-->
        <!--<ul>-->
          <!--<li><a href="#">link 1</a></li>-->
          <!--<li><a href="#">link 2</a></li>-->
          <!--<li><a href="#">link 3</a></li>-->
          <!--<li><a href="#">link 4</a></li>-->
        <!--</ul>-->
        <!--<h3>Search</h3>-->
        <!--<form method="post" action="#" id="search_form">-->
          <!--<p>-->
            <!--<input class="search" type="text" name="search_field" value="Enter keywords....." />-->
            <!--<input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="style/search.png" alt="Search" title="Search" />-->
          <!--</p>-->
        <!--</form>-->
      <!--</div>-->
      <div id="content">
          {% block main %}
          {% endblock %}
      </div>
        <div class="separator"></div>
        <p class="gsi-banner">Brought to you by:
        <a href="http://gsi.dit.upm.es"><img class="gsi-logo" src={{ url_for("static", filename="img/logo-gsi.png") }}/></a>
        </p>
    </div>
    <div id="footer">
        <p>
        This demonstrator has been made possible by the <a href="http://eurosentiment.eu"><span style="text-transform:uppercase;">eurosentiment project</span></a><br>
        Grant Agreement no:
        296277<br>
        Starting
        date:
        01/09/2012<br>
        Project
        duration:
        24
        months
        </p>

      <p class="copyright">Copyright &copy; textured_blue | <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.html5webtemplates.co.uk">design from HTML5webtemplates.co.uk</a>
      </p>
    </div>
  </div>
</body>
</html>

docon/templates/edit.html
{% extends 'admin/model/edit.html' %}
 
{% block tail %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename="css/codemirror.css" )}}"></link>
    <style type="text/css">.CodeMirror { border: 1px solid black;}</style>
    <script src="{{ url_for('static', filename="js/codemirror.js") }}"></script>
    <script src="{{ url_for('static', filename="js/mode/jinja2/jinja2.js") }}"></script>
    <script>
      var elements = document.getElementsByClassName("cmeditor");
      for(el in elements){
        console.log("CodeMirror:", elements[el]);
        var cm = CodeMirror.fromTextArea(elements[el], {
                lineNumbers: true,
                lineWrapping: false,
                column: 80,
                width: "10em",
                mode: {name: "jinja2", htmlMode: true}
                });
        cm.setOption("lineWrapping", true);
      }
    </script>
{% endblock %}

docon/templates/formats.html
{% extends 'base.html' %}

{% block main %}
<h1>Supported formats</h1>
<ul>
{% for format in formats %}
<li> {{ format.name }}
<ul>
    <li>{{ format.description | safe}}</li>
    {% if format.example %}
    <li> <a href="{{ url_for("frontend.serve_example", fmt=format.name) }}" >Example file</a> </li> 
    {% endif %}
</ul>
</li>
{% endfor %}
</ul>
<!--<h1>Templates available</h1>-->
<!--<ul>-->
{% for template in templates %}
<!--<li> {{ template.name }}-->
<!--<ul>-->
    <!--<li> Input: {{ template.informat }}</li>-->
    <!--<li> Output: {{ template.outformat }}</li>-->
<!--</ul>-->
<!--</li>-->
{% endfor %}
<!--</ul>-->

{% endblock %}

docon/templates/home.html
{% extends "base.html" %}

{% block main %}

<h1> Docon </h1>
<h2> A tool to convert files to different (semantic) formats </h2>

<p>This tool will take several input formats and translates them to <a
        href="http://gsi.dit.upm.es/ontologies/marl">MARL</a>, <a
        href="http://gsi.dit.upm.es/ontologies/onyx">ONYX</a> and other formats. Especially those in use in EUROSENTIMENT.
</p>

<p>
Docon is under heavy development. As of this writing, it supports:
<ul>
    <li>Creating and administrating translation templates (admin level)</li>
    <li>Editing templates to convert traditional formats (csv, tsv, xls)
    formats to Marl and Onyx</li>
    <li>Using the available templates to translate known formats through this
    portal or via POST requests</li>
    <li>Saving or outputting the result</li>
</ul>
</p>

<p>
In the future, we might include the following features:
<ul>
    <li>Conversion of semantic formats</li>
    <li>Automatic translation between semantic formats (e.g. RDF to JSON-LD)</li>
    <li>Auto selection of the best template based on the input format</li>
</ul>
</p>

{% endblock %}

docon/templates/index.html
<html>
    <body>
        <div>
            <a href="{{ url_for('admin.index') }}">Go to admin!</a>
        </div>
    </body>
</html>

docon/templates/my_master.html
{% extends 'admin/base.html' %}

{% block access_control %}
{% if current_user.is_authenticated() %}
<div class="btn-group pull-right">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-user"></i> {{ current_user.login }} <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="{{ url_for('admin.logout_view') }}">Log out</a></li>
    </ul>
</div>
{% endif %}
{% endblock %}

docon/templates/success.html
{% extends 'base.html' %}

{% block main %}

<a href="{{ file  }}">Download file!</a>

{% endblock %}

docon/templates/upload.html
{% extends 'base.html' %}

{% block extra_js %}
    <script>
        window.onload = function() {
            var intype = document.getElementById("intype");
            var inputtext = document.getElementById("inputtext");
            var inputfile = document.getElementById("inputfile");
            function setValues(){
                console.log("tweakform", intype);
                if( intype.value === 'file'){
                    console.log("Choosing file");
                    inputfile.parentNode.style.display = 'inline';
                    inputfile.removeAttribute("disabled");
                    inputtext.parentNode.style.display = 'none';
                    inputtext.setAttribute("disabled", true);
                }else{
                    console.log("Choosing text");
                    inputfile.setAttribute("disabled", true);
                    inputfile.parentNode.style.display = 'none';
                    inputtext.removeAttribute("disabled");
                    inputtext.parentNode.style.display = 'inline';
                }
            }
            setValues();
            intype.onchange = setValues;
        }
    </script>
{% endblock %}
{% block main %}
<h1>Format translation</h1>
<form action="{{ url_for('frontend.process') }}" method="post" enctype="multipart/form-data">

    <div><label for="intype">Input Type</label> <select id="intype" name="intype">
            <option selected="" value="file">File</option>
            <option value="url">Specify the file URL</option>
            <option value="direct">Direct</option></select>
    </div>
    <div><label>Text input</label><input id="inputtext" type="text" name="input"></input></div>
    <div><label>File input</label><input id="inputfile" type="file" name="input"></input></div>
    <div><label for="informat">Input format</label>
        <select id="informat" name="informat">
            {% for informat in informats %}
            <option value="{{ informat.name }}">{{ informat.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div><label for="outformat">Output format</label>
        <select id="outformat" name="outformat">
            {% for outformat in outformats %}
            <option value="{{ outformat[0] }}">{{ outformat[1] }}</option>
            {% endfor %}
        </select>
    </div>
    <div><label for="language">Language</label>
        <select id="language" name="language">
            <option value="">-- Select a language--</option>
            {% for language in languages %}
            <option value="{{ language[0] }}">{{ language[1] }}</option>
            {% endfor %}
        </select>
    </div>
    <div><label>Base URI:</label><input id="base" type="text" name="base"></input></div>
    <div><label>Timeout:</label><input id="timeout" type="number" name="timeout"></input></div>
<input type="submit" value="Submit" />
</form>

{% endblock %}